sonar.projectKey=ThanushaBai_devops-sonarqube-integration
sonar.organization=thanushabai

sonar.projectName=devops-sonarqube-integration
sonar.projectVersion=1.0
# Target Python version for accurate analysis
sonar.python.version=3.12
